name: Docker Build Check
on: 
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code 
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t iris-api . 